using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TestScript : MonoBehaviour
{
    [SerializeField]
    float speed;
    bool[] spinning =new bool[3];//ЉeѓЉЃ[ѓ‹‚Є‰с‚Б‚Д‚ў‚й‚©
    [SerializeField]
    Transform[] ReelsTF;

    bool f;
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        for(int i = 0; i < 3; i++)
        {
            if (spinning[i])
            {
                ReelsTF[i].Translate(Vector3.down * speed);
            }
            if (ReelsTF[i].position.y <= -2200)
            {
                Vector3 pos = ReelsTF[i].position;
                pos.y = 2400;
                ReelsTF[i].position = pos;
            }
        }
        if (f)
        {
            f = false;
            
        }
    }
    public void SpinReel()
    {
        f = true;

    }
    /// <summary>ѓ{ѓ^ѓ“‚р‰џ‚µ‚Ѕ‚Ж‚«‚МЏ€—ќ</summary>
    /// <param name="order">‰џ‚і‚к‚Ѕѓ{ѓ^ѓ“‚МЋЇ•К</param>
    public void StopReel(int order)
    {
        spinning[order] = false;
    }
}
